"""empty message

Revision ID: 3e089b55a6b9
Revises: 
Create Date: 2022-04-25 23:25:42.268565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e089b55a6b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_name'), 'author', ['name'], unique=False)
    op.create_table('database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_name'), 'database', ['name'], unique=True)
    op.create_table('doctype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctype_name'), 'doctype', ['name'], unique=True)
    op.create_table('publisher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publisher_name'), 'publisher', ['name'], unique=True)
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('publishing_year', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover', sa.String(length=255), nullable=True),
    sa.Column('isbn', sa.String(length=255), nullable=True),
    sa.Column('issn', sa.String(length=255), nullable=True),
    sa.Column('pages', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('udc', sa.String(length=255), nullable=True),
    sa.Column('bbk', sa.String(length=255), nullable=True),
    sa.Column('bibliographic_description', sa.Text(), nullable=True),
    sa.Column('database_id', sa.Integer(), nullable=True),
    sa.Column('doctype_id', sa.Integer(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['database.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctype_id'], ['doctype.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cover'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_record_bbk'), 'record', ['bbk'], unique=False)
    op.create_index(op.f('ix_record_isbn'), 'record', ['isbn'], unique=False)
    op.create_index(op.f('ix_record_issn'), 'record', ['issn'], unique=False)
    op.create_index(op.f('ix_record_udc'), 'record', ['udc'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('user_role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_role.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('records_authors',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('author_id', 'record_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records_authors')
    op.drop_table('user')
    op.drop_index(op.f('ix_record_udc'), table_name='record')
    op.drop_index(op.f('ix_record_issn'), table_name='record')
    op.drop_index(op.f('ix_record_isbn'), table_name='record')
    op.drop_index(op.f('ix_record_bbk'), table_name='record')
    op.drop_table('record')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_publisher_name'), table_name='publisher')
    op.drop_table('publisher')
    op.drop_index(op.f('ix_doctype_name'), table_name='doctype')
    op.drop_table('doctype')
    op.drop_index(op.f('ix_database_name'), table_name='database')
    op.drop_table('database')
    op.drop_index(op.f('ix_author_name'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
