"""database tables

Revision ID: a99ce894fa90
Revises: 
Create Date: 2022-04-19 23:45:02.553336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99ce894fa90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_index(op.f('ix_author_author_name'), 'author', ['author_name'], unique=False)
    op.create_table('doctype',
    sa.Column('doctype_id', sa.Integer(), nullable=False),
    sa.Column('doctype_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('doctype_id')
    )
    op.create_index(op.f('ix_doctype_doctype_name'), 'doctype', ['doctype_name'], unique=True)
    op.create_table('extdb',
    sa.Column('extdb_id', sa.Integer(), nullable=False),
    sa.Column('extdb_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('extdb_id')
    )
    op.create_index(op.f('ix_extdb_extdb_name'), 'extdb', ['extdb_name'], unique=False)
    op.create_table('publisher',
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('publisher_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('publisher_id')
    )
    op.create_index(op.f('ix_publisher_publisher_name'), 'publisher', ['publisher_name'], unique=True)
    op.create_table('user_role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('record',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('extdb', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.Integer(), nullable=True),
    sa.Column('cover', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('publishing_year', sa.SmallInteger(), nullable=True),
    sa.Column('isbn_issn', sa.String(length=17), nullable=True),
    sa.Column('num_pages', sa.SmallInteger(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('udk', sa.String(length=255), nullable=True),
    sa.Column('bbk', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('biblio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_type'], ['doctype.doctype_id'], ),
    sa.ForeignKeyConstraint(['extdb'], ['extdb.extdb_id'], ),
    sa.ForeignKeyConstraint(['publisher'], ['publisher.publisher_id'], ),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('cover'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_record_bbk'), 'record', ['bbk'], unique=True)
    op.create_index(op.f('ix_record_isbn_issn'), 'record', ['isbn_issn'], unique=True)
    op.create_index(op.f('ix_record_udk'), 'record', ['udk'], unique=True)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('user_role', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_role'], ['user_role.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('record_author',
    sa.Column('record_author_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.author_id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['record.record_id'], ),
    sa.PrimaryKeyConstraint('record_author_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_author')
    op.drop_table('user')
    op.drop_index(op.f('ix_record_udk'), table_name='record')
    op.drop_index(op.f('ix_record_isbn_issn'), table_name='record')
    op.drop_index(op.f('ix_record_bbk'), table_name='record')
    op.drop_table('record')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_publisher_publisher_name'), table_name='publisher')
    op.drop_table('publisher')
    op.drop_index(op.f('ix_extdb_extdb_name'), table_name='extdb')
    op.drop_table('extdb')
    op.drop_index(op.f('ix_doctype_doctype_name'), table_name='doctype')
    op.drop_table('doctype')
    op.drop_index(op.f('ix_author_author_name'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
